<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-04-09">

<title>Finance with SigAlg I: Introduction and binomial pricing models – john myers, ph.d.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../img/fav.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-367851019e9ccd243b94edaf001a4bfd.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4853ac07ca6a7896c17d72d590de6080.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-VWK3RHBGT2"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-VWK3RHBGT2', { 'anonymize_ip': true});
</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&amp;family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&amp;family=Nunito:ital,wght@0,200..1000;1,200..1000&amp;display=swap" rel="stylesheet">
<meta name="quarto:status" content="draft">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Finance with SigAlg I: Introduction and binomial pricing models">
<meta property="og:description" content="">
<meta property="og:image" content="https://johnmyers-phd.com/posts/finance-1/index_files/figure-html/cell-3-output-1.png">
<meta property="og:site_name" content="john myers, ph.d.">
<meta property="og:image:height" content="794">
<meta property="og:image:width" content="1187">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../writings.html"> 
<span class="menu-text">Writings</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="../../teaching/multi-calc-sp-26/multi-calc-sp-26.html">
 <span class="dropdown-text">Multivariable Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../teaching/pde-sp-26/pde-sp-26.html">
 <span class="dropdown-text">Partial Differential Equations</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://www.johnmyers-phd.com/book" target="_blank"> 
<span class="menu-text">Probabilistic Machine Learning</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.johnmyers-phd.com/sigalg" target="_blank"> 
<span class="menu-text">SigAlg</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/jmyers7/" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/john-myers-phd" target="_blank"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://bsky.app/profile/john-myers-phd.bsky.social" target="_blank"> <i class="bi bi-bluesky" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:jmmyers25@gmail.com"> <i class="bi bi-envelope-open-fill" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link active" data-scroll-target="#prerequisites">Prerequisites</a></li>
  <li><a href="#the-binomial-model" id="toc-the-binomial-model" class="nav-link" data-scroll-target="#the-binomial-model">The binomial model</a></li>
  <li><a href="#sigma-algebras-and-filtrations" id="toc-sigma-algebras-and-filtrations" class="nav-link" data-scroll-target="#sigma-algebras-and-filtrations"><span class="math inline">\(\sigma\)</span>-algebras and filtrations</a></li>
  <li><a href="#probability-measures" id="toc-probability-measures" class="nav-link" data-scroll-target="#probability-measures">Probability measures</a></li>
  <li><a href="#l2-spaces" id="toc-l2-spaces" class="nav-link" data-scroll-target="#l2-spaces"><span class="math inline">\(L^2\)</span>-spaces</a></li>
  <li><a href="#bibliography" id="toc-bibliography" class="nav-link" data-scroll-target="#bibliography">Bibliography</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Finance with SigAlg I: Introduction and binomial pricing models</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Finance</div>
    <div class="quarto-category">Pricing models</div>
    <div class="quarto-category">Binomial pricing models</div>
    <div class="quarto-category">Probability theory</div>
    <div class="quarto-category">Measure theory</div>
    <div class="quarto-category">Stochastic processes</div>
    <div class="quarto-category">Sigma-algebras</div>
    <div class="quarto-category">Filtrations</div>
    <div class="quarto-category">Conditional expectations</div>
    <div class="quarto-category">Hilbert spaces</div>
    <div class="quarto-category">Information theory</div>
    <div class="quarto-category">SigAlg</div>
    <div class="quarto-category">Python</div>
  </div>
  </div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>One of the core problems in mathematical finance is the construction of models of prices of financial assets, whether these be commodity assets like agricultural goods or precious metals, equity assets like stocks, or practically anything traded on a market. Price models serve multiple purposes, including forecasting future prices, allowing investors to (attempt to) turn a profit through speculation, or allowing a firm to hedge its position against an undesirable movement in the price of a business-critical asset. They may also be used to price a contract written on the asset from which it <em>derives</em> its value—such contracts are known, naturally, as <em>derivative</em> contracts. (We will explore these contracts in the next post in this series.) From a scientific perspective, an accurate price model can help lend insight into some of the underlying economic mechanisms that drive prices.</p>
<p>Of course, the ultimate driver of an asset price is “the market” itself, by which we mean the relative levels of supply and demand of the asset. But the supply and demand curves are themselves shaped by innumerable forces, all connected and interacting in unimaginably complex ways. There is an analogy here with statistical physics: Though we might understand the individual microscopic mechanics of an isolated molecule of a gas, and how it would interact with another (single) molecule, when that molecule is included in a container of the gas, the number of inter-molecular interactions is so large that the state of the gas must be modeled probabilistically. Indeed, one might, in principle, determine the exact future state of every molecule of the gas, but the lesson taught to us by statistical physics is that it is more advantageous to treat the movements of the individual molecules as <em>random</em>, and then familiar macroscopic properties of the gas (like temperature) emerge as statistical measures derived from the underlying probability distributions.</p>
<p>Thus, through analogy, we might imagine that if we had access to complete information on the forces that shape the supply and demand curves, then we could predict with exact precision the price movements of all the assets traded on a financial market. But this is obviously not possible, and so we resort to modeling the price movements as random, just as a physicist does with the molecules of their gas. To complete the analogy, “macroscopic properties” of the assets and the contracts written on them (like <em>risk-neutral prices</em>) emerge as statistical measures derived from the underlying probability distributions.</p>
<p>As with mathematical modeling of any sort, there is a trade-off between real-world accuracy and parsimony: Usually, the more accurate a model, the more complex it is, perhaps with many more parameters than a simpler but less accurate model. The two types of price models discussed in this post—<em>binomial</em> and <em>trinomial pricing models</em>—have extremely simple structure, depending on only a handful of parameters. But this doesn’t mean that they are not useful. In fact, as expert readers know, many of the intricate structures used in more complex price models are present in these basic models in simplified form, so a prior study of these models is beneficial.</p>
<p>This post introduces these two models through the new <code>finance</code> module of the <a href="https://johnmyers-phd.com/sigalg/">SigAlg</a> Python package for measure-theoretic probability. SigAlg is designed to be an interface between abstract mathematics and concrete code. Mathematical objects that one manipulates with pen and paper—probability measures, <span class="math inline">\(\sigma\)</span>-algebras, expectations and the like—all have representations in SigAlg, which differentiates it from purely computational Python libraries in which the underlying mathematical structures are left implicit. SigAlg directly exposes these structures.</p>
<section id="prerequisites" class="level3">
<h3 class="anchored" data-anchor-id="prerequisites">Prerequisites</h3>
<p>On the coding side, the prerequisites are minimal: The SigAlg API is written with fidelity to the mathematics as a core design principle, so as long as the reader can understand very basic Python and they have a good command of the mathematics, they should have little trouble following along with the code in this post.</p>
<p>On the mathematical side, the prerequisites are a bit steeper: We will freely use the language of basic measure-theoretic probability theory and stochastic process theory. We expect the reader to be familiar with probability measures, (filtered) <span class="math inline">\(\sigma\)</span>-algebras, (conditional) expectations, Radon-Nikodym derivatives, martingales, <em>etc</em>.</p>
</section>
<section id="the-binomial-model" class="level2">
<h2 class="anchored" data-anchor-id="the-binomial-model">The binomial model</h2>
<p>The <em>binomial price models</em> in this post are examples of <em>geometric processes</em>, by which we mean the following. Suppose that <span class="math inline">\(S_t\)</span> is a discrete-state stochastic process, with indices drawn from the discrete set <span class="math inline">\(t\in \{0,1,\ldots,T\}\)</span>, where <span class="math inline">\(T\)</span> is the <em>time horizon</em>. We imagine that <span class="math inline">\(S_t\)</span> is the price of an asset at time <span class="math inline">\(t\)</span>, with <span class="math inline">\(S_0\)</span> being the initial (constant) price. Then <span class="math inline">\(S_t\)</span> is a <em>geometric process</em> if there is a second process <span class="math inline">\(Z_t\)</span> such that, for each time <span class="math inline">\(t\geq 1\)</span>, we have</p>
<p><span id="eq-geo-model"><span class="math display">\[
S_t = S_{t-1}Z_t.
\tag{1}\]</span></span></p>
<p>The stochastic process <span class="math inline">\(Z_t\)</span> is called the <em>driving process</em> and it is required to be an IID process, which means that the random variables <span class="math inline">\(Z_1,Z_2,\ldots,Z_T\)</span> are independent and identically distributed. If we remember that a sequence of real numbers <span class="math inline">\(s_0,s_1,\ldots,s_T\)</span> is called a <em>geometric sequence</em> if there is a constant <span class="math inline">\(z\)</span> such that</p>
<p><span id="eq-geo-seq"><span class="math display">\[
s_t = s_{t-1}z
\tag{2}\]</span></span></p>
<p>for each <span class="math inline">\(t\geq 1\)</span>, then the reason <span class="math inline">\(S_t\)</span> is called a <em>geometric</em> process is clear upon comparison of (<a href="#eq-geo-model" class="quarto-xref">1</a>) and (<a href="#eq-geo-seq" class="quarto-xref">2</a>). (The random variable <span class="math inline">\(Z_t\)</span> is “constant” in the sense that it is drawn from an IID sequence.) Both the binomial models described in this post, and the trinomial models described in the next, are of the form (<a href="#eq-geo-model" class="quarto-xref">1</a>)—they only differ in the identity of their driving processes.</p>
<p>A geometric process may be contrasted with an <em>arithmetic process</em>, in which (<a href="#eq-geo-model" class="quarto-xref">1</a>) is replaced with the additive relation</p>
<p><span id="eq-arith-model"><span class="math display">\[
S_t = S_{t-1} + Z_t,
\tag{3}\]</span></span></p>
<p>where <span class="math inline">\(Z_t\)</span> is again an IID driving process. Of course, arithmetic processes are more commonly known as <em>random walks</em>.</p>
<p>Through a log transform, a geometric process satisfying (<a href="#eq-geo-model" class="quarto-xref">1</a>) may be converted into an arithmetic process:</p>
<p><span class="math display">\[
\log{S_t} = \log{S_{t-1}} + \log{Z_t}.
\]</span></p>
<p>Thus, if asset prices follow a geometric process, then the log prices are a random walk. This has financial implications, because analysts are often interested in the per-period <em>return</em> <span class="math inline">\((S_t-S_{t-1})/S_{t-1}\)</span> of an asset price. Using the usual tangent line approximation, we have</p>
<p><span class="math display">\[
\frac{S_t -S_{t-1}}{S_{t-1}} \approx \log{(S_t/S_{t-1})} = \log{S_t} - \log{S_{t-1}},
\]</span></p>
<p>and so returns are (approximately) the (backward) difference of a random walk process. But such differences are just IID processes:</p>
<p><span class="math display">\[
\log{S_t} - \log{S_{t-1}} = \log{Z_t}.
\]</span></p>
<p>Hence, if asset prices are modeled as a geometric process, then returns are modeled as an IID process.</p>
<p>Now, moving on to the central definition of this post:</p>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<div id="def-binomial" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1</strong></span> Let <span class="math inline">\(S_t\)</span> be a geometric process, with driving process <span class="math inline">\(Z_t\)</span>, and let <span class="math inline">\(u\)</span> and <span class="math inline">\(d\)</span> be two positive real numbers with <span class="math inline">\(d &lt; u\)</span>. Then <span class="math inline">\(S_t\)</span> is called a <em>binomial model</em> with <em>up-factor</em> <span class="math inline">\(u\)</span> and <em>down-factor</em> <span class="math inline">\(d\)</span> if the range of each <span class="math inline">\(Z_t\)</span> is <span class="math inline">\(\{u,d\}\)</span>.</p>
</div>
</div>
</div>
</div>
<p>Besides the initial price <span class="math inline">\(S_0\)</span> and the time horizon <span class="math inline">\(T\)</span>, a binomial model is parametrized by its up- and down-factors <span class="math inline">\(u\)</span> and <span class="math inline">\(d\)</span>. But there’s a fifth parameter hidden in the driving process: Indeed, by the IID assumption, there is a parameter <span class="math inline">\(p\)</span>, with <span class="math inline">\(0 &lt; p &lt; 1\)</span>, such that <span class="math inline">\(Z_t = u\)</span> with probability <span class="math inline">\(p\)</span>, and <span class="math inline">\(Z_t = d\)</span> with probability <span class="math inline">\(1-p\)</span> (for all <span class="math inline">\(t\)</span>). In the context of pricing, the probability <span class="math inline">\(p\)</span> is often called the <em>real-world probability</em>.</p>
<p>An example of a price trajectory (i.e., sample path) of a binomial model would be a sequence of prices of the form</p>
<p><span class="math display">\[
S_0 \xrightarrow{u} S_0u \xrightarrow{d} S_0 ud \xrightarrow{u} S_0u^2d.
\]</span></p>
<p>Thus, the complete set of <em>all</em> price trajectories of a binomial model with time horizon <span class="math inline">\(T\)</span> is in one-to-one correspondence with the set of all <span class="math inline">\(T\)</span>-tuples drawn from the set <span class="math inline">\(\{u,d\}\)</span>, and hence there are <span class="math inline">\(2^T\)</span> possible price trajectories. These price trajectories are often visualized as paths through a (sideways) binary tree. For example, suppose that we consider a binomial model with the parameters</p>
<p><span class="math display">\[
S_0 = 100, \quad u = 1.3, \quad d = 0.9, \quad T=3.
\]</span></p>
<p>Then there are two possible prices at <span class="math inline">\(t=1\)</span>, either</p>
<p><span class="math display">\[
S_0u = 130.00 \quad \text{or} \quad S_0d = 90.00.
\]</span></p>
<p>Similarly, there are three possible prices at <span class="math inline">\(t=2\)</span>, either</p>
<p><span class="math display">\[
S_0u^2 = 169.00, \quad S_0ud = 117.00, \quad \text{or} \quad S_0d^2 = 81.00.
\]</span></p>
<p>All <span class="math inline">\(2^3=8\)</span> possible price trajectories may be displayed as paths in the following tree, with an upward sloping edge corresponding to an up move (multiplication by <span class="math inline">\(u\)</span>), and a downward sloping edge corresponding to a down move (multiplication by <span class="math inline">\(d\)</span>).</p>
<div id="65a07e66" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="593" height="397"></p>
</figure>
</div>
</div>
</div>
<p>The mapping from price trajectories to terminal prices is many-to-one. For example, there are three trajectories leading to the final price <span class="math inline">\(152.10\)</span>, namely, those corresponding to the following sequences of up and down moves:</p>
<p><span class="math display">\[
(u, u, d), \quad (u, d, u), \quad \text{and} \quad (d, u, u).
\]</span></p>
<p>Turning to SigAlg, a binomial model is represented as an instance of the <code>BinomialPricingModel</code> class. Such an object is built using the parameters identified above, along with a parameter called <code>risk_free_rate</code>. We shall have much more to say about this latter parameter below, but for now, we set it equal to some value and then ignore it.</p>
<div id="58fa8173" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sigalg.core <span class="im">import</span> Time</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sigalg.finance <span class="im">import</span> BinomialPricingModel</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>S_0 <span class="op">=</span> <span class="dv">100</span>  <span class="co"># initial price</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> <span class="fl">0.05</span>  <span class="co"># risk-free rate — ignore for now</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> <span class="fl">0.7</span>  <span class="co"># real-world probability</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> <span class="fl">1.3</span>  <span class="co"># up-factor</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> <span class="fl">0.9</span>  <span class="co"># down-factor</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> <span class="dv">3</span>  <span class="co"># time horizon</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate a time index</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>time <span class="op">=</span> Time.discrete(length<span class="op">=</span>T)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate a binomial model</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>S <span class="op">=</span> BinomialPricingModel(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    initial_price<span class="op">=</span>S_0,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    risk_free_rate<span class="op">=</span>r,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    up_prob<span class="op">=</span>p,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    up_factor<span class="op">=</span>u,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    down_factor<span class="op">=</span>d,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    time<span class="op">=</span>time,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span><span class="st">"S"</span>,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The class <code>BinomialPricingModel</code> is a subclass of SigAlg’s <code>StochasticProcess</code>, and as such, each binomial pricing model carries two methods to generate price trajectories, namely <code>from_enumeration</code> and <code>from_simulation</code>. The latter method generates Monte Carlo simulations of price trajectories, while the former exhaustively enumerates all trajectories. We invoke this first method, and use SigAlg’s interface with Matplotlib to visualize the trajectories:</p>
<div id="a27f3dae" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>_, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">3</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>yellow <span class="op">=</span> <span class="st">"#FFC300"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>S.from_enumeration()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>S.plot_trajectories(ax<span class="op">=</span>ax, colors<span class="op">=</span>[yellow], y_label<span class="op">=</span><span class="st">"price"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="553" height="329"></p>
</figure>
</div>
</div>
</div>
<p>Notice that this printout is essentially the same as the binary tree displayed earlier, with four terminal prices. We can also print the price process itself:</p>
<div id="db41174e" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stochastic process 'S':
time          0      1      2      3
trajectory                          
0           100  130.0  169.0  219.7
1           100  130.0  169.0  152.1
2           100  130.0  117.0  152.1
3           100  130.0  117.0  105.3
4           100   90.0  117.0  152.1
5           100   90.0  117.0  105.3
6           100   90.0   81.0  105.3
7           100   90.0   81.0   72.9</code></pre>
</div>
</div>
<p>The printout shows the <span class="math inline">\(2^3 = 8\)</span> trajectories over the time period ending at <span class="math inline">\(T=3\)</span>, all beginning at the initial price <span class="math inline">\(S_0=100\)</span>. The trajectories are indexed by the set <span class="math inline">\(\Omega = \{0,1,\ldots,7\}\)</span>, which serves as the domain of the process:</p>
<div id="7793ab1e" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S.domain)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample space 'Omega':
[0, 1, 2, 3, 4, 5, 6, 7]</code></pre>
</div>
</div>
<p>The component random variables themselves <span class="math inline">\(S_t: \Omega \to \mathbb{R}\)</span> may be accessed via subscripting, which returns an instance of the <code>RandomVariable</code> class:</p>
<div id="7c5c27be" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S[<span class="dv">2</span>], <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)  <span class="co"># Print the random variable S_2</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S[<span class="dv">2</span>].domain, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)  <span class="co"># Check its domain</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(S[<span class="dv">2</span>]))  <span class="co"># Check its type</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random variable 'S_2':
              S_2
trajectory       
0           169.0
1           169.0
2           117.0
3           117.0
4           117.0
5           117.0
6            81.0
7            81.0 

Sample space 'Omega':
[0, 1, 2, 3, 4, 5, 6, 7] 

&lt;class 'sigalg.core.random_objects.random_variable.RandomVariable'&gt;</code></pre>
</div>
</div>
<p>The cardinality of the sample space <span class="math inline">\(\Omega\)</span> is <span class="math inline">\(2^T\)</span>, which scales exponentially with the time horizon. Obviously, this means that exhaustive enumeration of price trajectories is infeasible for large <span class="math inline">\(T\)</span>. SigAlg provides two options that the user can leverage for longer time horizons. The first is to operate the <code>from_enumeration</code> method in <code>sparse</code> enumeration mode. This requires that the down-factor <span class="math inline">\(d\)</span> is equal to the reciprocal up-factor, <span class="math inline">\(d = 1/u\)</span>, so that the binary tree is <em>recombining</em>. We make this adjustment in the next code block, and plot the sparsely enumerated trajectories over the same time horizon <span class="math inline">\(T=3\)</span> as before:</p>
<div id="f56754d2" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>S.down_factor <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> u  <span class="co"># Reset the down-factor</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>S.from_enumeration(enum_mode<span class="op">=</span><span class="st">"sparse"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>_, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">3</span>))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>S.plot_trajectories(ax<span class="op">=</span>ax, colors<span class="op">=</span>[yellow], y_label<span class="op">=</span><span class="st">"price"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stochastic process 'S':
time            0           1           2           3
trajectory                                           
0           100.0  130.000000  169.000000  219.700000
1           100.0   76.923077  100.000000  130.000000
2           100.0   76.923077   59.171598   76.923077
3           100.0   76.923077   59.171598   45.516614</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-2.png" class="quarto-figure quarto-figure-center figure-img" width="553" height="329"></p>
</figure>
</div>
</div>
</div>
<p>In <code>sparse</code> enumeration mode, the only price trajectories that are generated are those that consist first of a sequence entirely of down moves, followed by a sequence entirely of up moves. Every node/price in the binary tree is visited by one of these trajectories, and there are only <span class="math inline">\(T+1\)</span> of them, allowing one to generate all prices for large <span class="math inline">\(T\)</span>. One of the downsides—as we shall see in a later post—is that we cannot use a binomial model in <code>sparse</code> enumeration mode to price path-dependent contingent claims.</p>
<p>The other option available to the user for longer time horizons is to use the <code>from_simulation</code> method mentioned above, which randomly samples price trajectories according to the real-world probability measure (see the next section). The following code block gives an example of its usage over a (slightly) longer time horizon <span class="math inline">\(T=10\)</span>:</p>
<div id="c54d11a1" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>S.time <span class="op">=</span> Time.discrete(length<span class="op">=</span>T)  <span class="co"># Set a longer time horizon</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>S.down_factor <span class="op">=</span> d  <span class="co"># Reset to the original down-factor</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>S.from_simulation(n_trajectories<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>_, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">3</span>))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>S.plot_trajectories(ax<span class="op">=</span>ax, colors<span class="op">=</span>[yellow], y_label<span class="op">=</span><span class="st">"price"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" class="quarto-figure quarto-figure-center figure-img" width="553" height="329"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sigma-algebras-and-filtrations" class="level2">
<h2 class="anchored" data-anchor-id="sigma-algebras-and-filtrations"><span class="math inline">\(\sigma\)</span>-algebras and filtrations</h2>
<p>Every stochastic process <span class="math inline">\(S_t\)</span> is defined on an ambient probability space <span class="math inline">\((\Omega, \mathcal{F},P)\)</span>, where <span class="math inline">\(\mathcal{F}\)</span> is a <span class="math inline">\(\sigma\)</span>-algebra of events in the sample space <span class="math inline">\(\Omega\)</span> and <span class="math inline">\(P\)</span> is a probability measure defined on <span class="math inline">\(\mathcal{F}\)</span>. To be clear, this means that each function <span class="math inline">\(S_t:\Omega \to \mathbb{R}\)</span> is a random variable in the technical sense, i.e., each is <span class="math inline">\(\mathcal{F}\)</span>-measurable.</p>
<p>For the binomial models <span class="math inline">\(S_t\)</span> considered in this post, SigAlg automatically constructs the underlying probability space <span class="math inline">\((\Omega,\mathcal{F},P)\)</span>. The sample space <span class="math inline">\(\Omega\)</span> was described above: It consists simply of a finite index set <span class="math inline">\(\Omega = \{0,1,\ldots,n\}\)</span> up to some non-negative integer <span class="math inline">\(n\)</span>. As an example, the sample space for our first binomial model from the previous section is displayed in the first column of the following printout:</p>
<div id="14bcf41f" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>T <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>S.time <span class="op">=</span> Time.discrete(length<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>S.from_enumeration()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Stochastic process 'S':
time          0      1      2      3
trajectory                          
0           100  130.0  169.0  219.7
1           100  130.0  169.0  152.1
2           100  130.0  117.0  152.1
3           100  130.0  117.0  105.3
4           100   90.0  117.0  152.1
5           100   90.0  117.0  105.3
6           100   90.0   81.0  105.3
7           100   90.0   81.0   72.9</code></pre>
</div>
</div>
<p>The sample space is <span class="math inline">\(\Omega = \{0,1,\ldots,7\}\)</span>. The <span class="math inline">\(\sigma\)</span>-algebra is the power set on <span class="math inline">\(\Omega\)</span>:</p>
<div id="c6f31d41" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S.sigma_algebra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sigma algebra 'sigma(S)':
                                 atom ID
trajectory                              
0           (100.0, 130.0, 169.0, 219.7)
1           (100.0, 130.0, 169.0, 152.1)
2           (100.0, 130.0, 117.0, 152.1)
3           (100.0, 130.0, 117.0, 105.3)
4            (100.0, 90.0, 117.0, 152.1)
5            (100.0, 90.0, 117.0, 105.3)
6             (100.0, 90.0, 81.0, 105.3)
7              (100.0, 90.0, 81.0, 72.9)</code></pre>
</div>
</div>
<p>To understand the printout, we recall that every <span class="math inline">\(\sigma\)</span>-algebra on a <em>finite</em> sample space <span class="math inline">\(\Omega\)</span> is determined by its <em>atoms</em>, which are the minimal non-empty events. The atoms <span class="math inline">\(\{A_i\}_{i\in I}\)</span> (indexed by some finite set <span class="math inline">\(I\)</span>) partition the sample space <span class="math display">\[
\Omega = \bigcup_{i\in I} A_i.
\]</span></p>
<p>In SigAlg, <span class="math inline">\(\sigma\)</span>-algebras are represented by mappings <span class="math inline">\(\Omega \to I\)</span> from sample points <span class="math inline">\(\omega\)</span> to <em>atom identifiers</em> <span class="math inline">\(i\)</span>, where <span class="math inline">\(i\)</span> is the index of the unique atom <span class="math inline">\(A_i\)</span> that contains <span class="math inline">\(\omega\)</span>. In the printout above, the set <span class="math inline">\(I\)</span> of atom identifers is evidently the set of trajectories themselves, and so the atoms of the default <span class="math inline">\(\sigma\)</span>-algebra are all eight singletons. In other words, the <span class="math inline">\(\sigma\)</span>-algebra is indeed the power set.</p>
<p>Notice in the printout that the name of the default <span class="math inline">\(\sigma\)</span>-algebra is <span class="math inline">\(\sigma(S)\)</span>. The reader familiar with measure theory will recognize that this notation refers to the <span class="math inline">\(\sigma\)</span>-algebra <em>generated</em> by <span class="math inline">\(S\)</span>. In this context, we view the stochastic process as a <span class="math inline">\(4\)</span>-dimensional <em>random vector</em>:</p>
<p><span class="math display">\[
S: \Omega \to \mathbb{R}^4, \quad S(\omega) = (S_0(\omega),S_1(\omega), S_2(\omega), S_3(\omega)).
\]</span></p>
<p>Reflecting this view as a random vector, stochastic processes in SigAlg are actually callable; for example:</p>
<div id="52a26f34" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S(<span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Feature vector of '2':
          2
time       
0     100.0
1     130.0
2     117.0
3     152.1</code></pre>
</div>
</div>
<p>Note that this is precisely the trajectory <span class="math inline">\((S_0(2),S_1(2),S_2(2),S_3(2))\)</span> corresponding to the sample point <span class="math inline">\(2\in \Omega\)</span>.</p>
<p>Now, <span class="math inline">\(S\)</span> (as a random vector) generates a <span class="math inline">\(\sigma\)</span>-algebra whose atoms are precisely its nonempty level sets:</p>
<p><span class="math display">\[
S^{-1}(s) = \{ \omega \in \Omega \mid S(\omega) = s \},
\]</span></p>
<p>for <span class="math inline">\(s\in \mathbb{R}^4\)</span>. Notice that these level sets are indeed naturally indexed by <span class="math inline">\(4\)</span>-tuples <span class="math inline">\(s\)</span>, i.e., trajectories of the stochastic process.</p>
<p>In a similar way, each component random variable <span class="math inline">\(S_t\)</span> of the stochastic process (and indeed <em>every</em> random variable in SigAlg) induces its own <span class="math inline">\(\sigma\)</span>-algebra, denoted <span class="math inline">\(\sigma(S_t)\)</span>. As an example, in the following code block we print the atom identifiers of the <span class="math inline">\(\sigma\)</span>-algebra generated by the terminal price <span class="math inline">\(S_3\)</span>:</p>
<div id="95698835" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S[<span class="dv">3</span>].sigma_algebra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sigma algebra 'sigma(S_3)':
            atom ID
trajectory         
0             219.7
1             152.1
2             152.1
3             105.3
4             152.1
5             105.3
6             105.3
7              72.9</code></pre>
</div>
</div>
<p>Notice again that the atom identifiers are the values <span class="math inline">\(S_3(\omega)\)</span> of <span class="math inline">\(S_3\)</span> itself, reflecting the fact that the atoms are the nonempty level sets:</p>
<p><span class="math display">\[
S_3^{-1}(s) = \{\omega \in \Omega \mid S_3(\omega) = s\},
\]</span></p>
<p>for <span class="math inline">\(s\in \mathbb{R}\)</span>.</p>
<p>The power set <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\sigma(S)\)</span> shown above has the full trajectories of the stochastic process as its atom identifiers—but one can also use the “partial trajectories” as atom identifiers to construct <span class="math inline">\(\sigma\)</span>-algebras. In fact, this leads to a <em>filtration</em> of the <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\sigma(S)\)</span>, which is a nested sequence of the form</p>
<p><span class="math display">\[
\mathcal{F}_0 \subset \mathcal{F}_1 \subset \mathcal{F}_2 \subset \mathcal{F}_3 = \sigma(S),
\]</span></p>
<p>indexed over the same time horizon <span class="math inline">\(T=3\)</span>. In this particular case, with the partial trajectories as atom identifiers, we obtain the so-called <em>natural filtration</em> of the stochastic process. It is accessible via the corresponding attribute:</p>
<div id="7c498756" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>F <span class="op">=</span> S.natural_filtration</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Filtration (Ft)
===============

* Time 'T':
[0, 1, 2, 3]

* At time 0:
Sigma algebra '0':
            atom ID
trajectory         
0               100
1               100
2               100
3               100
4               100
5               100
6               100
7               100

* At time 1:
Sigma algebra '1':
                   atom ID
trajectory                
0           (100.0, 130.0)
1           (100.0, 130.0)
2           (100.0, 130.0)
3           (100.0, 130.0)
4            (100.0, 90.0)
5            (100.0, 90.0)
6            (100.0, 90.0)
7            (100.0, 90.0)

* At time 2:
Sigma algebra '2':
                          atom ID
trajectory                       
0           (100.0, 130.0, 169.0)
1           (100.0, 130.0, 169.0)
2           (100.0, 130.0, 117.0)
3           (100.0, 130.0, 117.0)
4            (100.0, 90.0, 117.0)
5            (100.0, 90.0, 117.0)
6             (100.0, 90.0, 81.0)
7             (100.0, 90.0, 81.0)

* At time 3:
Sigma algebra '3':
                                 atom ID
trajectory                              
0           (100.0, 130.0, 169.0, 219.7)
1           (100.0, 130.0, 169.0, 152.1)
2           (100.0, 130.0, 117.0, 152.1)
3           (100.0, 130.0, 117.0, 105.3)
4            (100.0, 90.0, 117.0, 152.1)
5            (100.0, 90.0, 117.0, 105.3)
6             (100.0, 90.0, 81.0, 105.3)
7              (100.0, 90.0, 81.0, 72.9)</code></pre>
</div>
</div>
<p>The printout shows the time index and the four <span class="math inline">\(\sigma\)</span>-algebras <span class="math inline">\(\mathcal{F}_t\)</span> (for <span class="math inline">\(t=0,1,2,3\)</span>). Notice that <span class="math inline">\(\mathcal{F}_3\)</span> coincides with <span class="math inline">\(\sigma(S)\)</span>, and that <span class="math inline">\(\mathcal{F}_0\)</span> is the <em>trivial <span class="math inline">\(\sigma\)</span>-algebra</em> whose only atom is the whole sample space <span class="math inline">\(\Omega\)</span> itself. Notice also that the atom identifiers of <span class="math inline">\(\mathcal{F}_t\)</span> are the length-<span class="math inline">\(t\)</span> partial trajectories. So, two sample points <span class="math inline">\(\omega,\omega'\in\Omega\)</span> are in the same atom of <span class="math inline">\(\mathcal{F}_t\)</span> if and only if the full trajectories that they correspond to agree at all times up to (and including) time <span class="math inline">\(t\)</span>, i.e.,</p>
<p><span id="eq-partial-traj"><span class="math display">\[
S_r(\omega) = S_r(\omega')
\tag{4}\]</span></span></p>
<p>for each <span class="math inline">\(r\leq t\)</span>. In view of (<a href="#eq-partial-traj" class="quarto-xref">4</a>), the <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\mathcal{F}_t\)</span> is often written as</p>
<p><span class="math display">\[
\mathcal{F}_t = \sigma( S_0, S_1, \ldots, S_t),
\]</span></p>
<p>and it is called the <span class="math inline">\(\sigma\)</span>-algebra <em>generated</em> by the random variables <span class="math inline">\(S_0,S_1,\ldots, S_t\)</span>.</p>
<p>The natural filtration is represented in SigAlg as an instance of the <code>Filtration</code> class. As such, it is subscriptable, allowing us to access the component <span class="math inline">\(\sigma\)</span>-algebras:</p>
<div id="81cdfb12" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(F[<span class="dv">1</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sigma algebra '1':
                   atom ID
trajectory                
0           (100.0, 130.0)
1           (100.0, 130.0)
2           (100.0, 130.0)
3           (100.0, 130.0)
4            (100.0, 90.0)
5            (100.0, 90.0)
6            (100.0, 90.0)
7            (100.0, 90.0)</code></pre>
</div>
</div>
<p>Finally, note that the “information” encoded in the <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\mathcal{F}_t\)</span> only allows to distinguish between trajectories based on their paths up to time <span class="math inline">\(t\)</span>. The <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\mathcal{F}_t\)</span> cannot “see into the future” beyond time <span class="math inline">\(t\)</span>. At one end of the time interval, <span class="math inline">\(\mathcal{F}_0\)</span> has only one atom, and so it cannot be used to distinguish between <em>any</em> of the trajectories. At the other end, <span class="math inline">\(\mathcal{F}_3\)</span> corresponds to the power set <span class="math inline">\(\sigma\)</span>-algebra, and so it contains enough information to distinguish between <em>all</em> of the trajectories.</p>
</section>
<section id="probability-measures" class="level2">
<h2 class="anchored" data-anchor-id="probability-measures">Probability measures</h2>
<p>Having described the sample space <span class="math inline">\(\Omega\)</span> and the <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\mathcal{F}\)</span> underlying our binomial model, we now turn to the probability measure <span class="math inline">\(P\)</span>. This will complete our description of the full probability space <span class="math inline">\((\Omega, \mathcal{F},P)\)</span>.</p>
<p>Recall that our model was instantiated with a real-world probability <span class="math inline">\(p=0.7\)</span>, which was the probability that the driving process takes the value <span class="math inline">\(Z_t=u\)</span>, where <span class="math inline">\(u\)</span> is the up-factor. This probability is accessible via the <code>up_prob</code> attribute:</p>
<div id="3bc15ce6" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S.up_prob)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.7</code></pre>
</div>
</div>
<p>Using the real-world probability <span class="math inline">\(p\)</span>, we define a discrete probability measure <span class="math inline">\(P\)</span> on the sample space by setting</p>
<p><span class="math display">\[
P(\{\omega\}) = p^k (1-p)^{T-k}
\]</span></p>
<p>for each <span class="math inline">\(\omega\in \Omega\)</span>, provided that <span class="math inline">\(\omega\)</span> corresponds to a trajectory with <span class="math inline">\(k\)</span> up moves and <span class="math inline">\(T-k\)</span> down moves. (Recall <span class="math inline">\(T\)</span> is the time horizon.) This probability measure is accessible using the <code>probability_measure</code> attribute of the binomial model, which returns an instance of SigAlg’s <code>ProbabilityMeasure</code> class:</p>
<div id="1200df11" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>P <span class="op">=</span> S.probability_measure</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(P, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)  <span class="co"># Print the measure</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">type</span>(P))  <span class="co"># Check its type</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability measure 'P':
            probability
trajectory             
0                 0.343
1                 0.147
2                 0.147
3                 0.063
4                 0.147
5                 0.063
6                 0.063
7                 0.027 

&lt;class 'sigalg.core.probability_measures.probability_measure.ProbabilityMeasure'&gt;</code></pre>
</div>
</div>
<p>For easy comparison, we can print the probabilities next to the trajectories:</p>
<div id="a117fda8" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>S.print_trajectories_and_probabilities()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              0      1      2      3  probability
trajectory                                       
0           100  130.0  169.0  219.7        0.343
1           100  130.0  169.0  152.1        0.147
2           100  130.0  117.0  152.1        0.147
3           100  130.0  117.0  105.3        0.063
4           100   90.0  117.0  152.1        0.147
5           100   90.0  117.0  105.3        0.063
6           100   90.0   81.0  105.3        0.063
7           100   90.0   81.0   72.9        0.027</code></pre>
</div>
</div>
<p>Thus, we see that the probability of the event <span class="math inline">\(A = \{0,7\}\)</span> is</p>
<p><span class="math display">\[
P(A) = 0.7^3 +0.3^3  = 0.37.
\]</span></p>
<p>We may perform the same computation in SigAlg:</p>
<div id="c6b3fbf0" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> S.domain.get_event([<span class="dv">0</span>, <span class="dv">7</span>])  <span class="co"># A is an `Event` object</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(P(A), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.37</code></pre>
</div>
</div>
<p>Probability measures in SigAlg may also be treated like probability mass functions and called directly on sample points:</p>
<div id="df89dd1e" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(P(<span class="dv">0</span>) <span class="op">+</span> P(<span class="dv">7</span>), <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.37</code></pre>
</div>
</div>
<p>When we extract component random variables, we inherit the probability measure. For example:</p>
<div id="0ea1ce76" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S[<span class="dv">3</span>].probability_measure)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability measure 'P':
            probability
trajectory             
0                 0.343
1                 0.147
2                 0.147
3                 0.063
4                 0.147
5                 0.063
6                 0.063
7                 0.027</code></pre>
</div>
</div>
<p>As we learned in our first course on probability theory, every random variable induces a <em>pushforward</em> (or <em>image</em>) <em>probability measure</em> on its range. In the case of the component random variable <span class="math inline">\(S_3\)</span>, this is the discrete measure <span class="math inline">\(P_{S_3}\)</span> on <span class="math inline">\(\mathbb{R}\)</span> defined by</p>
<p><span class="math display">\[
P_{S_3}(\{s\}) = P\left( \{\omega \in \Omega \mid S_3(\omega)=s\}\right),
\]</span></p>
<p>for each <span class="math inline">\(s\in \mathbb{R}\)</span>. The support of this measure is the range of <span class="math inline">\(S_3\)</span>, namely, the set of final prices <span class="math inline">\(\{72.90, 105.30, 152.10, 219.70\}\)</span>. To obtain the pushforward measure <span class="math inline">\(P_{S_3}\)</span> in SigAlg, we call the <code>pushforward</code> method:</p>
<div id="e26e50fd" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>S[<span class="dv">3</span>].pushforward()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>Probability measure 'P_S_3':
        probability
output             
72.9          0.027
105.3         0.189
152.1         0.441
219.7         0.343</code></pre>
</div>
</div>
</section>
<section id="l2-spaces" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="l2-spaces"><span class="math inline">\(L^2\)</span>-spaces</h2>
<div class="page-columns page-full"><p>The collection of all random variables on the probability space <span class="math inline">\((\Omega, \sigma(S), P)\)</span> underlying our binomial model constitute a finite-dimensional real vector space denoted <span class="math inline">\(L^2(\Omega,\sigma(S),P)\)</span>. Here, by a random variable “on the probability space,” we mean that each random variable must be <span class="math inline">\(\sigma(S)\)</span>-measurable. And, actually, in the general mathematical theory a function <span class="math inline">\(X: \Omega \to \mathbb{R}\)</span> must also be such that</p><div class="no-row-height column-margin column-container"><span class="margin-aside">If the reader recalls, <span class="math inline">\(\sigma(S)\)</span> is the power set <span class="math inline">\(\sigma\)</span>-algebra, and so <em>every</em> function on <span class="math inline">\(\Omega\)</span> is <span class="math inline">\(\sigma(S)\)</span>-measurable. But we will see examples below of <span class="math inline">\(L^2\)</span>-spaces built from coarser <span class="math inline">\(\sigma\)</span>-algebras, so we still prefer to explicitly state this condition.</span></div></div>
<p><span id="eq-square-integrable"><span class="math display">\[
\int_\Omega X^2 \, dP &lt; \infty
\tag{5}\]</span></span></p>
<p>in order to be in the <span class="math inline">\(L^2\)</span>-space, in addition to measurability. However, all sample spaces in SigAlg are finite and probability measures are discrete, so the Lebesgue integral above turns into a finite sum:</p>
<p><span class="math display">\[
\int_\Omega X^2 \, dP = \sum_{\omega \in \Omega} X(\omega)^2P(\{\omega\}).
\]</span></p>
<p>But the right-hand side is always <span class="math inline">\(&lt;\infty\)</span> in SigAlg, and hence this extra condition (<a href="#eq-square-integrable" class="quarto-xref">5</a>) is superfluous.</p>
<p>As the experienced reader knows, elements in an <span class="math inline">\(L^2\)</span>-space are often taken to be equivalence classes of random variables, where the equivalence relation is given by <em>almost sure equality</em>, meaning that two random variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are identified in the <span class="math inline">\(L^2\)</span>-space if they are equal everywhere except on an event of probability <span class="math inline">\(0\)</span>. However, in SigAlg, elements in an <span class="math inline">\(L^2\)</span>-space are actual random variables. For an example, let’s build the <span class="math inline">\(L^2\)</span>-space</p>
<p><span class="math display">\[
H = L^2(\Omega, \sigma(S),P)
\]</span></p>
<p>using the probability space from our binomial pricing model:</p>
<div id="0eeb4e88" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sigalg.l2 <span class="im">import</span> L2</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>H <span class="op">=</span> L2(</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    sample_space<span class="op">=</span>S.domain,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    sigma_algebra<span class="op">=</span>S.sigma_algebra,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    probability_measure<span class="op">=</span>S.probability_measure,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that S_3 is in H, for example</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S[<span class="dv">3</span>] <span class="kw">in</span> H)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>True</code></pre>
</div>
</div>
<p>The Lebesgue integral</p>
<p><span class="math display">\[
\int_A X \, dP = \sum_{\omega \in A} X(\omega) P(\{\omega\})
\]</span></p>
<p>of a random variable <span class="math inline">\(X\in H\)</span> over an event <span class="math inline">\(A\in \sigma(S)\)</span> is computable in SigAlg through an instance method of the <code>L2</code> class. For example, in the next code block we print out the trajectories of our binomial model along with the probability measure, and then compute <span class="math inline">\(\int_A S_3 \, dP\)</span>, where <span class="math inline">\(A = \{0,3\}\)</span>:</p>
<div id="f0160b2f" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>S.print_trajectories_and_probabilities()</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> S.domain.get_event([<span class="dv">0</span>, <span class="dv">3</span>])</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>integral <span class="op">=</span> H.integrate(rv<span class="op">=</span>S[<span class="dv">3</span>], event<span class="op">=</span>A)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The integral is"</span>, <span class="bu">round</span>(integral, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              0      1      2      3  probability
trajectory                                       
0           100  130.0  169.0  219.7        0.343
1           100  130.0  169.0  152.1        0.147
2           100  130.0  117.0  152.1        0.147
3           100  130.0  117.0  105.3        0.063
4           100   90.0  117.0  152.1        0.147
5           100   90.0  117.0  105.3        0.063
6           100   90.0   81.0  105.3        0.063
7           100   90.0   81.0   72.9        0.027
The integral is 81.991</code></pre>
</div>
</div>
<p>The <code>event</code> parameter of the <code>integrate</code> method is optional; if it is omitted, then the event defaults to the entire sample space <span class="math inline">\(A=\Omega\)</span>, and the Lebesgue integral is the expectation:</p>
<p><span class="math display">\[
E(X) = \int_\Omega X \, dP.
\]</span></p>
<p>In SigAlg:</p>
<div id="5d615ed9" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>expectation <span class="op">=</span> H.integrate(rv<span class="op">=</span>S[<span class="dv">3</span>])</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The expectation is"</span>, <span class="bu">round</span>(expectation, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The expectation is 164.303</code></pre>
</div>
</div>
<p>Alternatively, the expectation may be computed via the <code>expectation</code> method on the random variable itself; however, this method returns an instance of the <code>RandomVariable</code> class, and not a number:</p>
<div id="32eafc67" class="cell" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>expectation_rv <span class="op">=</span> S[<span class="dv">3</span>].expectation()</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(expectation_rv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random variable 'E(S_3)':
              E(S_3)
trajectory          
0           164.3032
1           164.3032
2           164.3032
3           164.3032
4           164.3032
5           164.3032
6           164.3032
7           164.3032</code></pre>
</div>
</div>
<p>Note that this is the <em>constant</em> random variable whose unique value is equal to the expectation computed via the integral. The reason that this method yields a random variable is to make it consistent with <em>conditional</em> expectations <span class="math inline">\(E(X\mid \mathcal{F})\)</span> as random variables, where <span class="math inline">\(\mathcal{F}\)</span> is a <span class="math inline">\(\sigma\)</span>-algebra contained in <span class="math inline">\(\sigma(S)\)</span>; see below. The unconditional expectation <span class="math inline">\(E(X)\)</span> is then obtained as the unique value of the random variable <span class="math inline">\(E(X \mid \{\emptyset, \Omega\})\)</span>, where the latter expectation is conditioned on the trivial <span class="math inline">\(\sigma\)</span>-algebra.</p>
<p>The theoretical interest in <span class="math inline">\(L^2\)</span>-spaces stems primarily from the rich mathematical structure that they carry—indeed, they are examples of <em>Hilbert spaces</em> when equipped with the inner product given by:</p>
<p><span class="math display">\[
\langle X, Y \rangle = \int_{\Omega} XY \, dP = \sum_{\omega \in \Omega} X(\omega)Y(\omega)P(\{\omega\}).
\]</span></p>
<p>This inner product is implemented in SigAlg as an instance method of the <code>L2</code> class:</p>
<div id="ef507776" class="cell" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the inner product of the random variables S_1 and S_2</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>inner_product <span class="op">=</span> H.inner(S[<span class="dv">1</span>], S[<span class="dv">2</span>])</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(inner_product, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>16826.8</code></pre>
</div>
</div>
<p>The induced norm of a random variable is defined by the equation</p>
<p><span class="math display">\[
\|X\|^2 = \langle X, X \rangle.
\]</span></p>
<p>This too is computable in SigAlg:</p>
<div id="8739d56a" class="cell" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the norm of the random variable S_1</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>norm <span class="op">=</span> H.norm(S[<span class="dv">1</span>])</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(norm, <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>119.415</code></pre>
</div>
</div>
<p>A basis for the vector space <span class="math inline">\(H\)</span> is given by the set of indicator functions of the atoms of <span class="math inline">\(\sigma(S)\)</span>. But recall that <span class="math inline">\(\sigma(S)\)</span> is the power set and <span class="math inline">\(\Omega\)</span> has cardinality <span class="math inline">\(8\)</span>; therefore, the <span class="math inline">\(L^2\)</span>-space has dimension <span class="math inline">\(8\)</span>:</p>
<div id="bc3ade2e" class="cell" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(H.dim)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>8</code></pre>
</div>
</div>
<p>An orthogonal basis of <span class="math inline">\(H\)</span> is given by the collection of indicator functions <span class="math inline">\(I_A:\Omega \to \mathbb{R}\)</span> of the atoms <span class="math inline">\(A\)</span> of the <span class="math inline">\(\sigma\)</span>-algebra, where</p>
<p><span class="math display">\[
I_A(\omega) = \begin{cases}
1 &amp; : \omega \in A, \\
0 &amp; : \omega \notin A.
\end{cases}
\]</span></p>
<p>So, an orthonormal basis of <span class="math inline">\(H\)</span> is given by the normalized indicator functions:</p>
<p><span class="math display">\[
\frac{I_A}{\|I_A\|} = \frac{1}{\sqrt{P(A)}} I_A,
\]</span></p>
<p>where <span class="math inline">\(A\)</span> varies over all atoms of <span class="math inline">\(\sigma(S)\)</span>.</p>
<p>The same types of orthnormal bases exist if we change the <span class="math inline">\(\sigma\)</span>-algebra of the <span class="math inline">\(L^2\)</span>-space. For example, let’s recall the <span class="math inline">\(\sigma\)</span>-algebra <span class="math inline">\(\mathcal{F}_1\)</span> from the previous section, with two atoms:</p>
<div id="b1f05b8f" class="cell" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(F[<span class="dv">1</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sigma algebra '1':
                   atom ID
trajectory                
0           (100.0, 130.0)
1           (100.0, 130.0)
2           (100.0, 130.0)
3           (100.0, 130.0)
4            (100.0, 90.0)
5            (100.0, 90.0)
6            (100.0, 90.0)
7            (100.0, 90.0)</code></pre>
</div>
</div>
<p>We define a second <span class="math inline">\(L^2\)</span>-space</p>
<p><span class="math display">\[
G = L^2(\Omega, \mathcal{F}_1, P)
\]</span></p>
<p>using this <span class="math inline">\(\sigma\)</span>-algebra:</p>
<div id="236e55a8" class="cell" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> L2(</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>    sample_space<span class="op">=</span>S.domain,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>    sigma_algebra<span class="op">=</span>F[<span class="dv">1</span>],</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    probability_measure<span class="op">=</span>S.probability_measure,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Since <span class="math inline">\(\mathcal{F}_1\)</span> has only two atoms, the orthonormal basis of <span class="math inline">\(G\)</span> described above consists of only two functions; they are accessible via the <code>basis</code> attribute, which returns a dictionary whose values are the normalized indicator functions:</p>
<div id="fde635da" class="cell" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>G_basis <span class="op">=</span> <span class="bu">list</span>(G.basis.values())</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> indicator <span class="kw">in</span> G_basis:</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(indicator)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random variable '(100.0, 130.0)':
            (100.0, 130.0)
trajectory                
0                 1.195229
1                 1.195229
2                 1.195229
3                 1.195229
4                 0.000000
5                 0.000000
6                 0.000000
7                 0.000000
Random variable '(100.0, 90.0)':
            (100.0, 90.0)
trajectory               
0                0.000000
1                0.000000
2                0.000000
3                0.000000
4                1.825742
5                1.825742
6                1.825742
7                1.825742</code></pre>
</div>
</div>
<p>Note that the names of the random variables are the atom identifiers, i.e., the partial trajectories of length <span class="math inline">\(1\)</span>.</p>
<p>Now, because <span class="math inline">\(\mathcal{F}_1\)</span> is a sub-<span class="math inline">\(\sigma\)</span>-algebra of <span class="math inline">\(\sigma(S)\)</span>, the vector space <span class="math inline">\(G\)</span> is a subspace of <span class="math inline">\(H\)</span>. In particular, the orthonormal basis of <span class="math inline">\(G\)</span> identified above is an orthonormal set in <span class="math inline">\(H\)</span>. Therefore, given a random variable <span class="math inline">\(X\in H\)</span>, its orthogonal projection <span class="math inline">\(\widehat{X}\)</span> onto <span class="math inline">\(G\)</span> is given by the familiar generalized Fourier expansion:</p>
<p><span class="math display">\[
\widehat{X} = \langle X, \phi_1 \rangle \phi_1 + \langle X, \phi_2 \rangle \phi_2,
\]</span></p>
<p>where <span class="math inline">\(\phi_1\)</span> and <span class="math inline">\(\phi_2\)</span> are the basis elements of <span class="math inline">\(G\)</span>. For example, in SigAlg we may use this <em>exact</em> formula to compute the orthogonal projection of <span class="math inline">\(S_3\)</span> onto <span class="math inline">\(G\)</span>:</p>
<div id="2cb1035b" class="cell" data-execution_count="34">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>S_3_hat <span class="op">=</span> <span class="bu">sum</span>(H.inner(S[<span class="dv">3</span>], phi) <span class="op">*</span> phi <span class="cf">for</span> phi <span class="kw">in</span> G_basis)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S_3_hat.with_name(<span class="st">"S_3_hat"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random variable 'S_3_hat':
            S_3_hat
trajectory         
0           181.012
1           181.012
2           181.012
3           181.012
4           125.316
5           125.316
6           125.316
7           125.316</code></pre>
</div>
</div>
<p>But the expert reader knows that orthogonal projections of random variables in <span class="math inline">\(L^2\)</span>-spaces are <em>exactly</em> conditional expectations. In fact, the random variable <span class="math inline">\(\widehat{S}_3\)</span> that we just computed is precisely <span class="math inline">\(E(S_3 \mid \mathcal{F}_1)\)</span>, the expectation of <span class="math inline">\(S_3\)</span> given <span class="math inline">\(\mathcal{F}_1\)</span>. These conditional expectations are directly computable in SigAlg by passing a value to the <code>sigma_algebra</code> parameter of the <code>expectation</code> method from above:</p>
<div id="9b5f6aae" class="cell" data-execution_count="35">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S[<span class="dv">3</span>].expectation(sigma_algebra<span class="op">=</span>F[<span class="dv">1</span>]))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Random variable 'E(S_3|1)':
            E(S_3|1)
trajectory          
0            181.012
1            181.012
2            181.012
3            181.012
4            125.316
5            125.316
6            125.316
7            125.316</code></pre>
</div>
</div>
<p>As we know from Hilbert space theory, the orthogonal projection <span class="math inline">\(\hat{S}_3\)</span> is the solution of an optimization problem:</p>
<p><span class="math display">\[
\widehat{S}_3 = \underset{Y \in G}{\operatorname{argmin}} \|Y - S_3\|^2.
\]</span></p>
<p>But a random variable is in <span class="math inline">\(G\)</span> if and only if it is <span class="math inline">\(\mathcal{F}_1\)</span>-measurable, and the norm may be expressed in terms of an expectation—therefore, the conditional expectation <span class="math inline">\(E(S_3 \mid \mathcal{F}_1)= \widehat{S}_3\)</span> minimizes the mean squared error</p>
<p><span class="math display">\[
E\left[(Y - S_3)^2\right]
\]</span></p>
<p>over all <span class="math inline">\(\mathcal{F}_1\)</span>-measurable random variables <span class="math inline">\(Y\)</span>.</p>
<div id="f7ec7d37" class="cell" data-execution_count="36">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>S.time <span class="op">=</span> Time.discrete(length<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>S.from_simulation(n_trajectories<span class="op">=</span><span class="dv">100_000</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(S.<span class="bu">range</span>.sample_space)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>68351</code></pre>
</div>
</div>
<div id="239d5987" class="cell" data-execution_count="37">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(S.<span class="bu">range</span>.probability_measure.data.values)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1.0e-05 1.0e-05 1.0e-05 ... 3.8e-04 2.9e-04 6.1e-04]</code></pre>
</div>
</div>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">Bibliography</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/johnmyers-phd\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>