---
title: "Multivariable calculus: Exercises"
toc: true
---

# 08 The definition of the derivative

## Exercise 1: Computing derivatives from the definition

Recall the definition of the *derivative* of a function $f: \mathbb{R}^n \to \mathbb{R}^m$ at a point $\mathbf{v}_0$ given in class:

$$
f'(\mathbf{v}_0) \mathbf{h} = \lim_{\lambda \to 0} \frac{f(\mathbf{v}_0 + \lambda\mathbf{h}) - f(\mathbf{v}_0)}{\lambda},
$$

for all $\mathbf{h}$ in $\mathbb{R}^n$.


::: {.callout-note icon="false" appearance="minimal"}

Using the above definition, compute the derivatives of the following functions.

a. $f: \mathbb{R}^2 \to \mathbb{R}$ given by $f(x,y) = x^2 - y^2$. Compute $f'(x,y)$.
b. $g: \mathbb{R}^2 \to \mathbb{R}$ given by $g(x,y) = 4-x^2-4y^2$. Compute $g'(x,y)$.
c. $q: \mathbb{R} \to \mathbb{R}^2$ given by $q(t) = (t + 2t^2, -t^3)$. Compute $q'(t)$.
d. $r: \mathbb{R} \to \mathbb{R}^3$ given by $r(t) = (e^t, \sin{t}, \cos{t})$. Compute $r'(t)$.
e. $u:\mathbb{R}^3 \to \mathbb{R}$ given by $u(x,y,z) = x^2 + y^2 + z^2$. Compute $u'(x,y,z)$.
f. $p: \mathbb{R}^2 \to \mathbb{R}^3$ given by $p(x,y) = (x^2, 3y, y^2)$. Compute $p'(x,y)$.
:::

::: {.callout-note collapse="true" icon="false"}
## Solutions.

a. $f'(x,y) = \begin{bmatrix} 2x & -2y \end{bmatrix}$.

b. $g'(x,y) = \begin{bmatrix} -2x & -8y \end{bmatrix}$.

c. $q'(t) = \begin{bmatrix} 1 + 4t \\ -3t^2 \end{bmatrix}$.

d. $r'(t) = \begin{bmatrix} e^t \\ \cos{t} \\ -\sin{t} \end{bmatrix}$.

e. $u'(x,y,z) = \begin{bmatrix} 2x & 2y & 2z \end{bmatrix}$.

f. $p'(x,y) = \begin{bmatrix} 2x & 0 \\ 0 & 3 \\ 0 & 2y \end{bmatrix}$.

:::

## Exercise 2: Computing tangent approximations and spaces

Recall that the *tangent space* to a function $f: \mathbb{R}^n \to \mathbb{R}^m$ at a point $\mathbf{v}_0$ is the range of the *tangent approximation* function:

$$
L_{\mathbf{v}_0}(\mathbf{v}) = f'(\mathbf{v}_0)(\mathbf{v} - \mathbf{v}_0) + f(\mathbf{v}_0).
$$

::: {.callout-note icon="false" appearance="minimal"}

This exercise refers to the functions defined in Exercise 1.

a. For $f(x,y) = x^2 - y^2$, compute the tangent approximation at the point $(x_0,y_0)=(1,0)$. Compute the tangent plane at this point as well, and check your answer using [Desmos](https://www.desmos.com/3d){target="_blank"}.

b. For $g(x,y) = 4-x^2-4y^2$, compute the tangent approximation at the point $(x_0,y_0)=(1,1)$. Compute the tangent plane at this point as well, and check your answer using [Desmos](https://www.desmos.com/3d){target="_blank"}.

c. For $q(t) = (t + 2t^2, -t^3)$, compute the tangent approximation at the point $t_0=1$. Compute the tangent line at this point as well, and check your answer using [Desmos](https://www.desmos.com/calculator){target="_blank"}.

d. For $r(t) = (e^t, \sin{t}, \cos{t})$, compute the tangent approximation at the point $t_0=0$. Compute the tangent line at this point as well, and check your answer using [Desmos](https://www.desmos.com/3d){target="_blank"}.

e. For $u(x,y,z) = x^2 + y^2 + z^2$, compute the tangent approximation at the point $(x_0,y_0,z_0)=(1,1,1)$.

f. For $p(x,y) = (x^2, 3y, y^2)$, compute the tangent approximation at the point $(x_0,y_0)=(1,1)$.

:::

::: {.callout-note collapse="true" icon="false"}
## Solutions.

a. The tangent approximation is
$$
L(x,y) = \begin{bmatrix} 2 & 0 \end{bmatrix} \begin{bmatrix} x-1 \\ y \end{bmatrix} + 1 = 2x - 1.
$$
The tangent plane is [here](https://www.desmos.com/3d/gkr9mtxtye){target="_blank"}.

b. The tangent approximation is
$$
L(x,y) = \begin{bmatrix} -2 & -8 \end{bmatrix} \begin{bmatrix} x-1 \\ y-1 \end{bmatrix} - 1 = -2x - 8y + 9.
$$
The tangent plane is [here](https://www.desmos.com/3d/vgof5c3hgl){target="_blank"}.

c. The tangent approximation is
$$
L(t) = \begin{bmatrix} 5 \\ -3 \end{bmatrix} (t-1) + \begin{bmatrix} 3 \\ -1 \end{bmatrix} = \begin{bmatrix} 5t - 2 \\ -3t + 2 \end{bmatrix}.
$$
The tangent line is [here](https://www.desmos.com/calculator/pskyyeoyxn){target="_blank"}.

d. The tangent approximation is
$$
L(t) = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} t + \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} t + 1 \\ t \\ 1 \end{bmatrix}.
$$
The tangent line is [here](https://www.desmos.com/3d/c2omdgxoa3){target="_blank"}.

e. The tangent approximation is
$$
L(x,y,z) = \begin{bmatrix} 2 & 2 & 2 \end{bmatrix} \begin{bmatrix} x-1 \\ y-1 \\ z-1 \end{bmatrix} + 3 = 2x + 2y + 2z - 3.
$$

f. The tangent approximation is
$$
L(x,y) = \begin{bmatrix} 2 & 0 \\ 0 & 3 \\ 0 & 2 \end{bmatrix} \begin{bmatrix} x-1 \\ y-1 \end{bmatrix} + \begin{bmatrix} 1 \\ 3 \\ 1 \end{bmatrix} = \begin{bmatrix} 2x - 1 \\ 3y \\ 2y - 1 \end{bmatrix}.
$$

:::

## Exercise 3: Normal and unit vectors

For this exercise, you'll need to remember the definition of *normal vectors* to planes, and *unit vectors*. Go back and look them up!

::: {.callout-note icon="false" appearance="minimal"}

a. In Exercise 2(a), you computed the tangent plane to the function $f$ at the specified point. Compute an upward-pointing unit normal vector. ("Upward-pointing" means that the $z$-component of the normal vector should be positive.) Check your answer using [Desmos](https://www.desmos.com/3d){target="_blank"}.

b. In Exercise 2(b), you computed the tangent plane to the function $g$ at the specified point. Compute an upward-pointing unit normal vector. Check your answer using [Desmos](https://www.desmos.com/3d){target="_blank"}.

c. In Exercise 2(c), you computed the tangent line to the function $q$ at the specified points. Compute a positively-oriented unit tangent vector at the point. ("Tangent vector" means it lies in the tangent line, and "positively-oriented" means that the vector points in the direction that the curve is traced out as $t$ increases.) Check your answer using [Desmos](https://www.desmos.com/calculator){target="_blank"}.

d. In Exercise 2(d), you computed the tangent line to the function $r$ at the specified points. Compute a positively-oriented unit tangent vector at the point. Check your answer using [Desmos](https://www.desmos.com/3d){target="_blank"}.

:::


::: {.callout-note collapse="true" icon="false"}
## Solutions.

a. The tangent plane for $f$ had equation $z = 2x-1$. Since this is in point-slope form, as we learned in class, an upward-pointing normal vector is
$$
\begin{bmatrix} -2 \\ 0 \\ 1 \end{bmatrix}.
$$
To make this a unit vector, we divide by its length:
$$
\mathbf{n} = \frac{1}{\sqrt{5}} \begin{bmatrix} -2 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} -\frac{2}{\sqrt{5}} \\ 0 \\ \frac{1}{\sqrt{5}} \end{bmatrix}.
$$
The graph is [here](https://www.desmos.com/3d/yfphw4b2mf){target="_blank"}.

b. The tangent plane for $g$ had equation $z = -2x - 8y + 9$. An upward-pointing normal vector is
$$
\begin{bmatrix} 2 \\ 8 \\ 1 \end{bmatrix}.
$$
To make this a unit vector, we divide by its length:
$$
\mathbf{n} = \frac{1}{\sqrt{69}} \begin{bmatrix} 2 \\ 8 \\ 1 \end{bmatrix} = \begin{bmatrix} \frac{2}{\sqrt{69}} \\ \frac{8}{\sqrt{69}} \\ \frac{1}{\sqrt{69}} \end{bmatrix}.
$$
The graph is [here](https://www.desmos.com/3d/ecgkgetgoi){target="_blank"}.

c. The tangent line for $q$ is the image of the function
$$
L(t) = \begin{bmatrix} 5 \\ -3 \end{bmatrix} (t-1) + \begin{bmatrix} 3 \\ -1 \end{bmatrix}.
$$
Thus, for all $t$, the vector
$$
L(t) - \begin{bmatrix} 3 \\ -1 \end{bmatrix} = \begin{bmatrix} 5 \\ -3 \end{bmatrix} (t-1)
$$
must lie in the tangent line. (Convince yourself of this by drawing a picture!) We may as well pick $t=2$ to get a nonzero vector in the tangent line:
$$
\begin{bmatrix} 5 \\ -3 \end{bmatrix}.
$$
This vector points in the direction that the curve is traced out as $t$ increases, so it is a positively-oriented tangent vector. To make it a unit vector, we divide by its length:
$$
\mathbf{t} = \frac{1}{\sqrt{34}} \begin{bmatrix} 5 \\ -3 \end{bmatrix} = \begin{bmatrix} \frac{5}{\sqrt{34}} \\ -\frac{3}{\sqrt{34}} \end{bmatrix}.
$$
The graph is [here](https://www.desmos.com/calculator/ah6o1iyopp){target="_blank"}.

d. The tangent line for $r$ is the image of the function
$$
L(t) = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} t + \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}.
$$
Thus, for all $t$, the vector
$$
L(t) - \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix} = \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} t
$$
must lie in the tangent line. We may as well pick $t=1$ to get a nonzero vector in the tangent line:
$$
\begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}.
$$
This vector points in the direction that the curve is traced out as $t$ increases, so it is a positively-oriented tangent vector. To make it a unit vector, we divide by its length:
$$
\mathbf{t} = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} \\ 0 \end{bmatrix}.
$$
The graph is [here](https://www.desmos.com/3d/yginexykos){target="_blank"}.

:::

## Exercise 4: Using derivatives to approximate changes

Recall from the class that the derivative of a function $f: \mathbb{R}^n \to \mathbb{R}^m$ at a point $\mathbf{v}_0$ can be used to approximate changes in the value of $f$ near $\mathbf{v}_0$. Specifically, for $\mathbf{h}$ small, we have
$$
f(\mathbf{v}_0 + \mathbf{h}) - f(\mathbf{v}_0) \approx f'(\mathbf{v}_0) \mathbf{h}.
$$

::: {.callout-note icon="false" appearance="minimal"}

For each of the six functions in Exercise 1, use the derivative to approximate the following changes in function values. Compare your approximations to the true values.

a. $f: \mathbb{R}^2 \to \mathbb{R}$ given by $f(x,y) = x^2 - y^2$. Compute $f'(x,y)$.
b. $g: \mathbb{R}^2 \to \mathbb{R}$ given by $g(x,y) = 4-x^2-4y^2$. Compute $g'(x,y)$.
c. $q: \mathbb{R} \to \mathbb{R}^2$ given by $q(t) = (t + 2t^2, -t^3)$. Compute $q'(t)$.
d. $r: \mathbb{R} \to \mathbb{R}^3$ given by $r(t) = (e^t, \sin{t}, \cos{t})$. Compute $r'(t)$.
e. $u:\mathbb{R}^3 \to \mathbb{R}$ given by $u(x,y,z) = x^2 + y^2 + z^2$. Compute $u'(x,y,z)$.
f. $p: \mathbb{R}^2 \to \mathbb{R}^3$ given by $p(x,y) = (x^2, 3y, y^2)$. Compute $p'(x,y)$.

---

a. $f(1.2,0.98) - f(1.1,1.0)$.
b. $g(1.17,0.98) - g(1.15,1.01)$.
c. $q(1.24) - q(1.2)$.
d. $r(5.35) - r(5.26)$.
e. $u(4.2,0.32,18.5) - u(4.13,0.42,18.3)$.
f. $p(-21.2,0.34) - p(-21.8,0.33)$.

:::

::: {.callout-note collapse="true" icon="false"}
## Solutions.

a. True value: $0.2696$. Approximation: $0.26$.

b. True value: $0.1924$. Approximation: $0.1964$.

c. True value: $\begin{bmatrix} 0.2352 \\ -0.178624\end{bmatrix}$. Approximation: $\begin{bmatrix} 0.232 \\ -0.1728 \end{bmatrix}$.

d. True value: $\begin{bmatrix}18.1268 \\ 0.0502506 \\ 0.0746285\end{bmatrix}$. Approximation: $\begin{bmatrix} 17.3233 \\ 0.0468584 \\ 0.0768394 \end{bmatrix}$.

e. True value: $7.8691$. Approximation: $7.8142$.

f. True value: $\begin{bmatrix}-25.8 \\ 0.03 \\ 0.0067\end{bmatrix}$. Approximation: $\begin{bmatrix}-26.16 \\ 0.03 \\ 0.0066\end{bmatrix}$.

:::
