---
title: "17 Sturm-Liouville problems, part 2"
format:
    revealjs:
        incremental: true
        slide-number: true
        theme:
            - default
            - "../../aux-files/custom-slides.scss"
---

## Separated boundary conditions {.scrollable}


- We recall the setup from the previous slides. We consider the linear second-order differential operator $L$ given by
$$
L(f) = r f'' + r' f' + pf.
$$
    a. We suppose that $r$ and $p$ are real functions on $[a,b]$, each with continuous second derivatives.
    b. We suppose that $r(x)\neq 0$ for all $x\in [a,b]$.
    c. We suppose that the domain of $L$ is the set of all functions $f$ on $[a,b]$ (possibly complex valued) with continuous second derivatives.

- By Langrange's identity, we saw that (provided $r(a)=r(b)$) if we restrict $L$ to those functions $f$ that satisfy the **periodic boundary conditions**
$$
f(a) =f(b) \quad \text{and} \quad f'(a) =f'(b),
$$
then $L$ is self-adjoint.

- We may also consider **separated boundary conditions**, which are of the form
$$
\alpha_1 f(a) + \alpha_2 f'(a) =0 \quad \text{and} \quad \beta_1 f(b) + \beta_2 f'(b) =0,
$$
for some $\alpha_1,\alpha_2,\beta_1,\beta_2\in \mathbb{R}$, where not both $\alpha_1$ and $\alpha_2$ are $0$ simultaneously, and similarly for $\beta_1$ and $\beta_2$.

## Exercise 1: Separated boundary conditions imply self-adjoint {.scrollable}

::: {.callout-note icon="false" .nonincremental appearance="minimal"}

Suppose we restrict $L$ to those functions that satisfy separated boundary conditions. Show that $L$ is self-adjoint.

:::

## Regular Sturm-Liouville problems {.scrollable}

::: {.callout-note icon="false" .nonincremental  .fragment}

### Definition

A **regular Sturm-Liouville problem** is given by the following:

a. A second-order linear differential operator $L$ of the previous form.
b. A set of boundary conditions, either periodic or separated, with respect to which $L$ is self-adjoint.
b. A (real) positive, continuous weight function $w$ on $[a,b]$.

Then the object is to find all solutions $f$ of the boundary value problem
$$
L(f) + \lambda w f = 0,
$$
where $\lambda$ is an arbitrary constant and $f$ satisfies the given boundary conditions.

:::

- Clearly a (regular) Sturm-Liouville problem always has the **trivial solution** $f=0$. 

- If $f$ is a **nontrivial solution** (i.e., $f\neq 0$), then $f$ is called an **eigenfunction** and the corresponding $\lambda$ is called an **eigenvalue**.

- Linear combinations of eigenfunctions with the same eigenvalue are again eigenfunctions, so together with the trivial solution every eigenvalue $\lambda$ has a corresponding subspace of eigenfunctions called its **eigenspace**.

## The "Spectral Theorems" of regular Sturm-Liouville problems {.scrollable}

::: {.callout-note icon="false" .nonincremental  .fragment}

### Theorem 3.9

Let a regular Sturm-Liouville problem be given.

a. All eigenvalues are real.

b. Eigenfunctions corresponding to distinct eigenvalues are orthogonal in $L^2_w(a,b)$.

c. The eigenspace for any eigenvalue $\lambda$ is at most $2$-dimensional. If the boundary conditions are separated, it is always $1$-dimensional.

:::

::: {.callout-note icon="false" .nonincremental  .fragment}

### Theorem 3.10

For every regular Sturm-Liouville problem on $[a,b]$:

a. The set of eigenvalues is countably infinite. 
b. There is an orthonormal basis $\{\phi_n\}_{n=1}^\infty$ of $L^2_w(a,b)$ consisting of eigenfunctions.

:::

## Exercise 1: A simple Sturm-Liouville problem {.scrollable}

::: {.callout-note icon="false" .nonincremental appearance="minimal"}

Consider the boundary value problem

$$
f'' + \lambda f= 0, \quad f(0) = f(\ell) = 0,
$$

for some $\ell>0$.

a. Identify this as a regular Sturm-Liouville problem. What types of boundary conditions are these?

b. Find all eigenvalues and eigenfunctions of the problem.

:::