---
title: "Partial Differential Equations: Exercises"
toc: true
---

# 02 Separation of variables

## Exercise 1: Separating variables in the heat equation with different boundary conditions

In class, we "solved" the heat equation in the form of the following boundary-value problem:

$$
\frac{\partial u}{\partial t} = k \frac{\partial^2 u}{\partial x^2},
$$

with

$$
u(0,t) = 0 \quad \text{and} \quad u(L,t) = 0, \quad t > 0.
$$ {#eq-class-bvp}

In this problem, instead of the boundary conditions ([-@eq-class-bvp]), we will consider the boundary conditions

$$
\frac{\partial u}{\partial x}(0,t) = 0 \quad \text{and} \quad \frac{\partial u}{\partial x}(L,t) = 0, \quad t > 0.
$$ {#eq-new-bvp}

Again, notice that these are *not* initial conditions, since we only require $t>0$.

::: {.callout-note icon="false" appearance="minimal"}

a. Suppose that we have our metal rod lying along the $x$-axis from $x = 0$ to $x = L$, and that $u(x,t)$ models the temperature at position $x$ and time $t$. What do the new boundary conditions ([-@eq-new-bvp]) imply about the behavior of the temperature at the ends of the rod?

b. With the first set of boundary conditions ([-@eq-class-bvp]), in class we found the "solution"
$$
u(x,t) = \sum_{n=1}^{\infty} a_n \exp\left(\frac{-n^2 \pi^2 kt}{L^2} \right) \sin\left( \frac{n \pi x}{L} \right)
$$
by separation of variables. How does this "solution" change if we use the new boundary conditions ([-@eq-new-bvp]) instead? 

:::
::: {.callout-note collapse="true" icon="false"}
## Solutions.

a. At any *fixed* time $t>0$, the derivatives in ([-@eq-new-bvp]) are the slopes of the tangent lines at $x=0$ and $x=L$ to the graph of $u(x,t)$, plotted in the $(x,u)$-plane. The boundary conditions tell us that these slopes are both $0$, so the tangent lines are horizontal. This means that there is no "heat flow" into or out of the rod through the ends. Why? Take a simple example—consider the end of the rod at $x=0$. If there was heat flow *into* the rod from values $x<0$, then the slope at $x=0$ must be negative, since heat "flows" from higher to lower temperatures. Similarly, if there was heat flow *out of* the rod at $x=0$, the slope would be positive. A similar analysis holds at the other end, where $x=L$. We summarize all of this by saying that the boundary conditions ([-@eq-new-bvp]) correspond to *insulated ends*, meaning no heat can enter or leave the rod through its endpoints.

b. Basically, I'm telling you to solve the heat equation again, by separating variables. The main difference is now you'll have the system of ODEs given by
$$
T'(t) = -k \lambda T(t), \quad X''(x) +\lambda X(x)=0
$$
with the boundary conditions
$$
X'(0) = 0 \quad \text{and} \quad X'(L) = 0.
$$
The general solution to the first is still
$$
T(t) = C_0 \exp(-k \lambda t),
$$
while the general solution to the second is
$$
X(x) = C_1 \cos(\sqrt{\lambda} x) + C_2 \sin(\sqrt{\lambda} x).
$$
The boundary condition $X'(0)=0$ tells us that $C_2 = 0$, so
$$
X(x) = C_1 \cos(\sqrt{\lambda} x).
$$
The boundary condition $X'(L)=0$ then gives
$$
-\sqrt{\lambda} C_1 \sin(\sqrt{\lambda} L) = 0,
$$
which implies that either $C_1 = 0$ or $\sin(\sqrt{\lambda} L) = 0$. The nontrivial solutions correspond to
$$
\sqrt{\lambda} L = n \pi, \quad n = 0, \pm 1, \pm 2, \pm 3, \dots
$$
so
$$
\lambda = \left(\frac{n \pi}{L}\right)^2.
$$
Therefore, for each $n=0,1,2,3,\dots$, we have a solution
$$
X_n(x) = \cos\left(\frac{n \pi x}{L}\right).
$$
Then, just as in class, this means that the infinite series "solution" is of the form
$$
u(x,t) = \sum_{n=0}^{\infty} a_n \exp\left(\frac{-n^2 \pi^2 kt}{L^2} \right) \cos\left( \frac{n \pi x}{L} \right).
$$

:::


## Exercise 2: Solving the heat equation with real numbers

In this exercise, you will solve the heat equation with real numbers and real initial conditions. Assume that the infinite series "solutions" that we have discovered by separating variables really are *solutions*, and that there are no problems with convergence.

::: {.callout-note icon="false" appearance="minimal"}

Imagine a metal rod lying along the $x$-axis from $x=0$ to $x=\pi$. Solve the heat equation

$$
\frac{\partial u}{\partial t} = \frac{\partial^2 u}{\partial x^2},
$$

with boundary conditions
$$
\frac{\partial u}{\partial x}(0,t) = 0 \quad \text{and} \quad \frac{\partial u}{\partial x}(\pi,t) = 0, \quad t > 0,
$$

and initial condition
$$
u(x,0) = \cos{2x} +5\cos{3x}, \quad 0 \le x \le \pi.
$$

Then, once you have your solution $u(x,t)$, make an animation in [Desmos](https://www.desmos.com/calculator) by plotting the solution in the $(x,u)$-plane with a slider for $t$.


:::
::: {.callout-note collapse="true" icon="false"}
## Solutions.

From the previous exercise, we know that the general solution to the heat equation will be

$$
u(x,t) = \sum_{n=0}^{\infty} a_n \exp\left(-n^2 t \right) \cos{nx },
$$

since $k=1$ and $L=\pi$. We have

$$
u(x,0) = \sum_{n=0}^{\infty} a_n\cos{n x },
$$

which must equal the initial condition $u(x,0) = \cos{2x} +5\cos{3x}$, and so
$$
\cos{2x} +5\cos{3x} = \sum_{n=0}^{\infty} a_n\cos{n x }.
$$

By equating coefficients on both sides, we get that $a_2 = 1$, $a_3 = 5$, and $a_n = 0$ for all other $n$. Therefore, the solution we seek is
$$
u(x,t) = \exp(-4t) \cos(2x) + 5 \exp(-9t) \cos(3x).
$$
:::

## Exercise 3: Solving the wave equation

Recall that the wave equation is
$$
\frac{\partial^2 u}{\partial t^2} = a^2 \frac{\partial^2 u}{\partial x^2},
$$

where $a>0$ is a constant. Let's suppose that we impose the boundary conditions
$$
u(0,t) = 0 \quad \text{and} \quad u(L,t) = 0, \quad t > 0,
$$

where $L>0$ is a fixed length.

::: {.callout-note icon="false" appearance="minimal"}

Just as with the heat equation, we may "solve" the wave equation by separation of variables, to obtain an infinite series "solution". Do it!

:::
::: {.callout-note collapse="true" icon="false"}
## Solutions.

We suppose that we have a solution of the form
$$
u(x,t) = X(x)T(t).
$$

Substituting this into the wave equation, we get
$$
X(x) T''(t) = a^2 X''(x) T(t).
$$
Dividing both sides by $a^2 X(x) T(t)$, we obtain
$$
\frac{T''(t)}{a^2 T(t)} = \frac{X''(x)}{X(x)} = -\lambda,
$$
where $\lambda$ is a (real number) constant. This leads us to the system of two ODEs
$$
T''(t) + a^2 \lambda T(t) = 0, \quad X''(x) + \lambda X(x) = 0,
$$

with boundary conditions $X(0)=0$ and $X(L)=0$. The general solution to the first equation is
$$
T(t) = C_1\sin(\sqrt{\lambda}a t) + C_2\cos(\sqrt{\lambda}a t),
$$

while the general solution to the second equation is

$$
X(x) = C_3 \sin(\sqrt{\lambda} x) + C_4 \cos(\sqrt{\lambda} x).
$$

The boundary condition $X(0)=0$ implies $C_4 = 0$, so we have

$$
X(x) = C_3 \sin(\sqrt{\lambda} x).
$$

Then, since $X(L)=0$, we must have

$$
\sqrt{\lambda} L = n \pi, \quad n = 1, 2, 3, \dots
$$

just as in the case of the heat equation. So, for each $n=1,2,3,\dots$, we have a solution
$$
X_n(x) = \sin\left(\frac{n \pi x}{L}\right).
$$
Then, just as in class, this means that the infinite series "solution" is of the form
$$
u(x,t) = \sum_{n=1}^{\infty} \left[ a_n \cos\left(\frac{n \pi a t}{L}\right) + b_n \sin\left(\frac{n \pi a t}{L}\right) \right] \sin\left(\frac{n \pi x}{L}\right),
$$

for some constants $a_n$ and $b_n$.

:::

## Exercise 4: The Laplacian and Laplace's equation

Let $u(x_1,x_2,\ldots,x_n)$ be a real-valued function of $n$ real variables with continuous second-order partial derivatives. The *Laplacian* is the differential operator $\nabla^2$ that acts on $u$ as
$$
\nabla^2 u = \sum_{k=1}^n \frac{\partial^2 u}{\partial x_k^2} =  \frac{\partial^2 u}{\partial x_1^2} + \frac{\partial^2 u}{\partial x_2^2} + \cdots + \frac{\partial^2 u}{\partial x_n^2}.
$$

For example, for a function of the form $u(x,y)$, the Laplacian of $u$ is
$$
\nabla^2 u = \frac{\partial^2 u}{\partial x^2} + \frac{\partial^2 u}{\partial y^2},
$$

while for a function of the form $u(x)$, the Laplacian of $u$ is simply the second derivative:

$$
\nabla^2 u = \frac{d^2 u}{dx^2}.
$$

If $u$ has "space" variables as well as a "time" variable $t$, then the Laplacian only acts on the space variables, not on $t$. For example, for a function of the form $u(x,t)$, we have

$$
\nabla^2 u(x,t) = \frac{\partial^2 u}{\partial x^2}(x,t).
$$

Therefore, the heat and wave equations may equivalently be written as

$$
\frac{\partial u}{\partial t} = \nabla^2 u \quad \text{and} \quad \frac{\partial^2 u}{\partial t^2} = \nabla^2 u,
$$

respectively.

In any number of variables, *Laplace's equation* is the linear, homogeneous, second-order partial differential equation
$$
\nabla^2 u = 0.
$$
Solutions to Laplace's equation are called *harmonic functions*.

::: {.callout-note icon="false" appearance="minimal"}

a. Is the Laplacian a *linear* differential operator?

b. Compute the Laplacians of the following functions:
    i. $u(x,y) = x^2 + y^2$
    ii. $u(x,y,z) = 2x^2\sin{y} + e^z$
    iii. $u(x) = x^2e^x$
    iv. $u(x,y,t) = x^2yt + y^2t + t^2\cos{x}$

c. Find all single-variable harmonic functions $u(x)$ on the unit interval $[0,1]$ subject to the boundary conditions $u(0)=a$ and $u(1)=b$ (for some constants $a$ and $b$).

d. Consider Laplace's equation for functions $u(x,y)$ on the rectangle
$$
0 \leq x \leq 2\pi, \quad 0 \leq y \leq 1,
$$
in $\mathbb{R}^2$. Suppose we impose the boundary conditions
$$
u(x,0) = \sin{x}-\sin\left(\frac{3x}{2}\right) \quad \text{and} \quad u(x,1) = e\sin{x} - e^{3/2}\sin\left(\frac{3x}{2}\right)
$$
along the bottom and top edges of the rectangle (draw the rectangle in the $xy$-plane), and
$$
u(0,y) = 0, \quad u(2\pi,y) = 0
$$
along the left and right edges of the rectangle. Using separation of variables, solve Laplace's equation. Plot your solution using [Desmos](https://www.desmos.com/3d){target="_blank"}.

:::
::: {.callout-note collapse="true" icon="false"}
## Solutions.

a. Yes. This is because the Laplacian is
$$
\nabla^2 = \sum_{k=1}^n \frac{\partial^2}{\partial x_k^2}
$$
which is a sum of all the second-order partial derivative operators, and the latter are known (from calculus!) to be linear.

b. 

c. In one variable, the Laplacian is just the second derivative, so we need to solve the ODE
$$
u''(x)=0.
$$
One application of the Fundamental Theorem of Calculus gives us
$$
u'(x) - u'(0) = \int_0^x u''(s) \, ds = 0,
$$
and so $u'(x) = u'(0)$. But then another application of the same theorem yields
$$
u(x) - u(0) = \int_0^x u'(0) \, ds = u'(0) x,
$$
and so
$$
u(x) = u'(0) x + u(0).
$$
However, the boundary conditions $u(0)=a$ and $u(1)=b$ imply
$$
u(0) = u'(0) \cdot 0 + u(0) = a \quad \text{and} \quad u(1) = u'(0) \cdot 1 + u(0) = b,
$$
so we must have $u(0) = a$ and $u'(0) = b - a$. Therefore, the solution is
$$
u(x) = (b-a)x + a.
$$
Thus, there is only *one* harmonic function on the unit interval $[0,1]$ that satisfies the given boundary conditions, namely, the linear function that passes through the points $(0,a)$ and $(1,b)$.

d. Suppose that $u$ factors as
$$
u(x,y) = X(x)Y(y).
$$
Substituting this into Laplace's equation gives
$$
X''(x)Y(y) + X(x)Y''(y) = 0.
$$
Rearranging and dividing both sides by $X(x)Y(y)$ gives
$$
\frac{X''(x)}{X(x)} =- \frac{Y''(y)}{Y(y)}.
$$
Since the left-hand side is a function only of $x$, and the right-hand side is a function only of $y$, each side must be equal to a nonzero real constant, say $-\lambda$. Then
$$
\frac{X''(x)}{X(x)} = -\lambda \quad \text{and} \quad \frac{Y''(y)}{Y(y)} = \lambda,
$$
which gives us the system of two ODEs
$$
X''(x) + \lambda X(x) = 0, \quad Y''(y) - \lambda Y(y) = 0.
$$
The boundary conditions translate to
$$
X(x)Y(0) = \sin{x}-\sin\left(\frac{3x}{2}\right) \quad \text{and} \quad X(x)Y(1)=e\sin{x} - e^{3/2}\sin\left(\frac{3x}{2}\right), 
$$
along with
$$
\quad X(0)Y(y)=0 \quad \text{and} \quad X(2\pi)Y(y)=0.
$$
Now, this part is a little different than the heat and wave equations, since we must consider two cases: either $\lambda<0$ or $\lambda>0$.
    - If $\lambda<0$, then we may set $\lambda = -a^2$, for some nonzero real number $a$. Then the general solution to the $X$-equation is
    $$
    X(x) = C_1 e^{ax},
    $$
    while the general solution to the $Y$-equation is
    $$
    Y(y) = C_2 \sin{ay} + C_3 \cos{ay}.
    $$
    But then the boundary condition $X(x)Y(0)=0$ implies
    $$
    C_1C_3 e^{ax} = \sin{x}-\sin\left(\frac{3x}{2}\right)
    $$
    for all $0\leq x \leq 2\pi$. But this is impossible, and hence we cannot have $\lambda<0$.
    - So, we assume $\lambda>0$. In this case, we set $\lambda = a^2$, for some nonzero real number $a$. Then the general solution to the $X$-equation is
    $$
    X(x) = C_1 \sin{ax} + C_2 \cos{ax},
    $$
    while the general solution to the $Y$-equation is
    $$
    Y(y) = C_3 e^{ay}.
    $$
    Then the boundary condition $X(0)Y(y)=0$ implies that $C_2 = 0$, so we must have
    $$
    X(x) = C_1 \sin{ax}.
    $$
    The boundary condition $X(2\pi)Y(y)=0$ implies that $C_1 \sin{2\pi a} = 0$, so we must have $a = n/2$ for some integer $n$. Therefore, for each $n=1,2,\ldots$, we get a solution
    $$
    u_n(x,y) = \sin\left(\frac{nx}{2}\right) \exp\left( \frac{ny}{2}  \right)
    $$
    to Laplace's equation. By comparing these solutions to the boundary conditions, we determine that our desired solution is the superposition
    $$
    u(x,y) = u_2(x,y) - u_3(x,y) = \sin{x} \exp{y} - \sin\left(\frac{3x}{2}\right) \exp\left( \frac{3y}{2} \right).
    $$


:::